name: Converter Postman para OpenAPI

on:
  push:
    paths:
      - 'Postman Collections/zproapi.json'
  workflow_dispatch:

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Instalar conversor localmente
        # Instalamos sem o -g. Ele vai criar uma pasta invisível chamada node_modules
        run: npm install postman-to-openapi
        
      - name: Converter para YAML
        # Chamamos o arquivo executável p2o apontando o caminho físico exato dele! Zero confusão.
        run: ./node_modules/.bin/p2o "./Postman Collections/zproapi.json" -f ./openapi.yaml
        
      - name: Salvar o YAML no GitHub
        run: |
          git config --global user.name "Robô de Conversão"
          git config --global user.email "action@github.com"
          git add openapi.yaml
          git commit -m "Auto-convertendo Postman para OpenAPI" || exit 0
          git push
